// <auto-generated />
namespace MyFinance.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fluentApi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fluentApi));
        
        string IMigrationMetadata.Id
        {
            get { return "201610061046067_fluentApi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
